### ISSUE TITLE
Compiling Merlin-agent separately cannot be launched into the Mythic project. How to implement custom compilation and linkage

### ISSUE THREAD

**Issue by boomaad** [Ne0nd0g/merlin-agent#42]
Compiling Merlin-agent separately cannot be launched into the Mythic project. How to implement custom compilation and linkage

**Comment by Ne0nd0g** [comment]
@boomaad Merlin agents used with Mythic must be compiled from within Mythic. This is because Mythic creates a UUID per payload that needs to be provided at compile time. After you build a Merlin agent from within Mythic, you can go to the "Payloads" page and click the "Actions" button and then "View Build Message/Stdout" to retrieve the the command you can use to manually compile the agent. You need to build this agent from the `https://github.com/MythicAgents/merlin/tree/main/Payload_Type/merlin/agent` directory.

Here is an example:
> Build: go build -o merlin.bin -buildmode=default -ldflags '-s -w -X "main.payloadID=ac9e52a0-9bff-436c-b6f6-90a6ddaa9891" -X "main.profile=http" -X "main.httpClient=go" -X "main.url=https://127.0.01:443/data" -X "main.psk=YtU0tpdmSs8KG0QUnXkxyqhk4r380j9umxQGBXaQEPI=" -X "main.useragent=Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko" -X "main.sleep=10s" -X "main.skew=2300" -X "main.killdate=1753488000" -X "main.maxretry=7" -X "main.padding=4096" -X "main.verbose=false" -X "main.debug=false" -buildid=' -tags=mythic main.go

You might need to manually a single quote `'` before the `-s` argument and at the end of the `-buildid=` argument.
